abyss_server:
- http://abyss.htek.com:5001/
abyss_upgrade_url:
- http://10.3.3.49/fw/abyss/daily_na/
download_daily_rom_url:
- http://repo.htek.com:8810/job/elpis_dev_new/578/artifact/out/roms/neutral/
download_output_url:
- http://abyss-dl.htek.com/.task/635a966e-bf8f-11ec-8995-000c29ffac12/output/
import_cfg_path:
- C:/Users/admin/Desktop
import_rom_path:
- C:/Users/admin/Desktop
password:
- admin:admin
- Administrator:9102SerCloudPBX
- user:1234
- admin:7267
register_date:
- 3cx 1501:
    Authenticate: 1501
    sip_password: 222222
    sip_server: 192.168.0.68
    sip_user: 1501
- 3cx 1502:
    Authenticate: 1502
    sip_password: 222222
    sip_server: 192.168.0.68
    sip_user: 1502
- 3cx 1503:
    Authenticate: 1503
    sip_password: 222222
    sip_server: 192.168.0.68
    sip_user: 1503
- 3cx 1504:
    Authenticate: 1504
    sip_password: 222222
    sip_server: 192.168.0.68
    sip_user: 1504
- free 1501:
    Authenticate: 1501
    sip_password: 222222
    sip_server: 192.168.0.10
    sip_user: 1501
- free 1502:
    Authenticate: 1502
    sip_password: 222222
    sip_server: 192.168.0.10
    sip_user: 1502
- free 1503:
    Authenticate: 1503
    sip_password: 222222
    sip_server: 192.168.0.10
    sip_user: 1503
- free 1504:
    Authenticate: 1504
    sip_password: 222222
    sip_server: 192.168.0.10
    sip_user: 1504
save_output_path:
- G:/HTTP/fw/abyss/daily_file/
- C:/Users/admin/Desktop/
save_rom_path:
- G:/HTTP/fw/abyss/daily_na/
- G:/HTTP/fw/abyss/daily_654/
- C:/Users/admin/Desktop/
