# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(214, 825)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(6, 9, 201, 731))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 171, 131))
        self.D1_text_ip = QLineEdit(self.groupBox_2)
        self.D1_text_ip.setObjectName(u"D1_text_ip")
        self.D1_text_ip.setGeometry(QRect(62, 20, 101, 20))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 41, 16))
        self.D1_btn_band = QPushButton(self.groupBox_2)
        self.D1_btn_band.setObjectName(u"D1_btn_band")
        self.D1_btn_band.setGeometry(QRect(10, 80, 151, 23))
        self.D1_lab_state = QLabel(self.groupBox_2)
        self.D1_lab_state.setObjectName(u"D1_lab_state")
        self.D1_lab_state.setGeometry(QRect(10, 110, 54, 12))
        self.D1_lab_online = QLabel(self.groupBox_2)
        self.D1_lab_online.setObjectName(u"D1_lab_online")
        self.D1_lab_online.setGeometry(QRect(80, 110, 54, 12))
        self.D1_box_password = QComboBox(self.groupBox_2)
        self.D1_box_password.setObjectName(u"D1_box_password")
        self.D1_box_password.setGeometry(QRect(10, 50, 151, 22))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 150, 171, 141))
        self.D1_btn_autotest = QPushButton(self.groupBox_3)
        self.D1_btn_autotest.setObjectName(u"D1_btn_autotest")
        self.D1_btn_autotest.setGeometry(QRect(10, 20, 75, 23))
        self.D1_btn_telnet = QPushButton(self.groupBox_3)
        self.D1_btn_telnet.setObjectName(u"D1_btn_telnet")
        self.D1_btn_telnet.setGeometry(QRect(90, 20, 75, 23))
        self.D1_btn_reboot = QPushButton(self.groupBox_3)
        self.D1_btn_reboot.setObjectName(u"D1_btn_reboot")
        self.D1_btn_reboot.setGeometry(QRect(10, 50, 75, 23))
        self.D1_btn_factory = QPushButton(self.groupBox_3)
        self.D1_btn_factory.setObjectName(u"D1_btn_factory")
        self.D1_btn_factory.setGeometry(QRect(90, 50, 75, 23))
        self.pushButton = QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 80, 75, 23))
        self.pushButton_2 = QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 110, 75, 23))
        self.pushButton_3 = QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(90, 80, 75, 23))
        self.pushButton_4 = QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(90, 110, 75, 23))
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 300, 171, 161))
        self.D1_text_fw = QLineEdit(self.groupBox)
        self.D1_text_fw.setObjectName(u"D1_text_fw")
        self.D1_text_fw.setGeometry(QRect(10, 40, 151, 20))
        self.D1_btn_ap = QPushButton(self.groupBox)
        self.D1_btn_ap.setObjectName(u"D1_btn_ap")
        self.D1_btn_ap.setGeometry(QRect(10, 120, 151, 23))
        self.D1_text_cfg = QLineEdit(self.groupBox)
        self.D1_text_cfg.setObjectName(u"D1_text_cfg")
        self.D1_text_cfg.setGeometry(QRect(10, 90, 151, 20))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 54, 12))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 70, 54, 12))
        self.label_5.setFrameShape(QFrame.NoFrame)
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 580, 171, 131))
        self.D1_check_3cx0 = QCheckBox(self.groupBox_4)
        self.D1_check_3cx0.setObjectName(u"D1_check_3cx0")
        self.D1_check_3cx0.setGeometry(QRect(10, 20, 71, 16))
        self.D1_check_3cx1 = QCheckBox(self.groupBox_4)
        self.D1_check_3cx1.setObjectName(u"D1_check_3cx1")
        self.D1_check_3cx1.setGeometry(QRect(10, 40, 71, 16))
        self.D1_check_3cx2 = QCheckBox(self.groupBox_4)
        self.D1_check_3cx2.setObjectName(u"D1_check_3cx2")
        self.D1_check_3cx2.setGeometry(QRect(10, 60, 71, 16))
        self.D1_check_3cx3 = QCheckBox(self.groupBox_4)
        self.D1_check_3cx3.setObjectName(u"D1_check_3cx3")
        self.D1_check_3cx3.setGeometry(QRect(10, 80, 71, 16))
        self.D1_check_fre1 = QCheckBox(self.groupBox_4)
        self.D1_check_fre1.setObjectName(u"D1_check_fre1")
        self.D1_check_fre1.setGeometry(QRect(90, 40, 71, 16))
        self.D1_check_fre0 = QCheckBox(self.groupBox_4)
        self.D1_check_fre0.setObjectName(u"D1_check_fre0")
        self.D1_check_fre0.setGeometry(QRect(90, 20, 71, 16))
        self.D1_check_fre3 = QCheckBox(self.groupBox_4)
        self.D1_check_fre3.setObjectName(u"D1_check_fre3")
        self.D1_check_fre3.setGeometry(QRect(90, 80, 71, 16))
        self.D1_check_fre2 = QCheckBox(self.groupBox_4)
        self.D1_check_fre2.setObjectName(u"D1_check_fre2")
        self.D1_check_fre2.setGeometry(QRect(90, 60, 71, 16))
        self.D1_btn_register = QPushButton(self.groupBox_4)
        self.D1_btn_register.setObjectName(u"D1_btn_register")
        self.D1_btn_register.setGeometry(QRect(10, 100, 151, 23))
        self.groupBox_9 = QGroupBox(self.tab)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 470, 171, 101))
        self.label_2 = QLabel(self.groupBox_9)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 54, 12))
        self.label_3 = QLabel(self.groupBox_9)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(90, 20, 54, 12))
        self.D1_text_pnum = QLineEdit(self.groupBox_9)
        self.D1_text_pnum.setObjectName(u"D1_text_pnum")
        self.D1_text_pnum.setGeometry(QRect(10, 40, 61, 20))
        self.D1_text_pvalue = QLineEdit(self.groupBox_9)
        self.D1_text_pvalue.setObjectName(u"D1_text_pvalue")
        self.D1_text_pvalue.setGeometry(QRect(80, 40, 81, 20))
        self.D1_btn_pselect = QPushButton(self.groupBox_9)
        self.D1_btn_pselect.setObjectName(u"D1_btn_pselect")
        self.D1_btn_pselect.setGeometry(QRect(10, 70, 61, 23))
        self.D1_btn_pset = QPushButton(self.groupBox_9)
        self.D1_btn_pset.setObjectName(u"D1_btn_pset")
        self.D1_btn_pset.setGeometry(QRect(80, 70, 81, 23))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_5 = QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 280, 171, 161))
        self.D2_text_fw = QLineEdit(self.groupBox_5)
        self.D2_text_fw.setObjectName(u"D2_text_fw")
        self.D2_text_fw.setGeometry(QRect(10, 40, 151, 20))
        self.D2_btn_ap = QPushButton(self.groupBox_5)
        self.D2_btn_ap.setObjectName(u"D2_btn_ap")
        self.D2_btn_ap.setGeometry(QRect(10, 120, 151, 23))
        self.D2_text_cfg = QLineEdit(self.groupBox_5)
        self.D2_text_cfg.setObjectName(u"D2_text_cfg")
        self.D2_text_cfg.setGeometry(QRect(10, 90, 151, 20))
        self.label_6 = QLabel(self.groupBox_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 20, 54, 12))
        self.label_7 = QLabel(self.groupBox_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 70, 54, 12))
        self.label_7.setFrameShape(QFrame.NoFrame)
        self.groupBox_6 = QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 150, 171, 121))
        self.D2_btn_autotest = QPushButton(self.groupBox_6)
        self.D2_btn_autotest.setObjectName(u"D2_btn_autotest")
        self.D2_btn_autotest.setGeometry(QRect(10, 20, 75, 23))
        self.D2_btn_telnet = QPushButton(self.groupBox_6)
        self.D2_btn_telnet.setObjectName(u"D2_btn_telnet")
        self.D2_btn_telnet.setGeometry(QRect(90, 20, 75, 23))
        self.D2_btn_reboot = QPushButton(self.groupBox_6)
        self.D2_btn_reboot.setObjectName(u"D2_btn_reboot")
        self.D2_btn_reboot.setGeometry(QRect(10, 50, 75, 23))
        self.D2_btn_factory = QPushButton(self.groupBox_6)
        self.D2_btn_factory.setObjectName(u"D2_btn_factory")
        self.D2_btn_factory.setGeometry(QRect(90, 50, 75, 23))
        self.groupBox_7 = QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 10, 171, 131))
        self.D2_text_ip = QLineEdit(self.groupBox_7)
        self.D2_text_ip.setObjectName(u"D2_text_ip")
        self.D2_text_ip.setGeometry(QRect(62, 20, 101, 20))
        self.label_8 = QLabel(self.groupBox_7)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 41, 16))
        self.D2_btn_band = QPushButton(self.groupBox_7)
        self.D2_btn_band.setObjectName(u"D2_btn_band")
        self.D2_btn_band.setGeometry(QRect(10, 80, 151, 23))
        self.D2_lab_state = QLabel(self.groupBox_7)
        self.D2_lab_state.setObjectName(u"D2_lab_state")
        self.D2_lab_state.setGeometry(QRect(10, 110, 54, 12))
        self.D2_lab_online = QLabel(self.groupBox_7)
        self.D2_lab_online.setObjectName(u"D2_lab_online")
        self.D2_lab_online.setGeometry(QRect(80, 110, 54, 12))
        self.D2_box_password = QComboBox(self.groupBox_7)
        self.D2_box_password.setObjectName(u"D2_box_password")
        self.D2_box_password.setGeometry(QRect(10, 50, 151, 22))
        self.groupBox_8 = QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 450, 171, 171))
        self.D2_check_3cx0 = QCheckBox(self.groupBox_8)
        self.D2_check_3cx0.setObjectName(u"D2_check_3cx0")
        self.D2_check_3cx0.setGeometry(QRect(10, 20, 71, 16))
        self.D2_check_3cx1 = QCheckBox(self.groupBox_8)
        self.D2_check_3cx1.setObjectName(u"D2_check_3cx1")
        self.D2_check_3cx1.setGeometry(QRect(90, 20, 71, 16))
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 214, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bdd\u673aIP", None))
        self.D1_btn_band.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u8bbe\u5907", None))
        self.D1_lab_state.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u72b6\u6001\uff1a", None))
        self.D1_lab_online.setText(QCoreApplication.translate("MainWindow", u"\u672a\u7ed1\u5b9a", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u533a", None))
        self.D1_btn_autotest.setText(QCoreApplication.translate("MainWindow", u"AutoTest", None))
        self.D1_btn_telnet.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u6a21\u5f0f", None))
        self.D1_btn_reboot.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u8bdd\u673a", None))
        self.D1_btn_factory.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u51fa\u5382", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u5347\u7ea7", None))
        self.D1_btn_ap.setText(QCoreApplication.translate("MainWindow", u"AP", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"fw\u8def\u5f84", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"cfg\u8def\u5f84", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u4fe1\u606f", None))
        self.D1_check_3cx0.setText(QCoreApplication.translate("MainWindow", u"3cx 1500", None))
        self.D1_check_3cx1.setText(QCoreApplication.translate("MainWindow", u"3cx 1501", None))
        self.D1_check_3cx2.setText(QCoreApplication.translate("MainWindow", u"3cx 1502", None))
        self.D1_check_3cx3.setText(QCoreApplication.translate("MainWindow", u"3cx 1503", None))
        self.D1_check_fre1.setText(QCoreApplication.translate("MainWindow", u"fre 1501", None))
        self.D1_check_fre0.setText(QCoreApplication.translate("MainWindow", u"fre 1500", None))
        self.D1_check_fre3.setText(QCoreApplication.translate("MainWindow", u"fre 1503", None))
        self.D1_check_fre2.setText(QCoreApplication.translate("MainWindow", u"fre 1502", None))
        self.D1_btn_register.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"P\u503c\u914d\u7f6e", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"P\u503c(int)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.D1_btn_pselect.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.D1_btn_pset.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6eP\u503c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u8bbe\u59071", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u5347\u7ea7", None))
        self.D2_btn_ap.setText(QCoreApplication.translate("MainWindow", u"AP", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"fw\u8def\u5f84", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"cfg\u8def\u5f84", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u533a", None))
        self.D2_btn_autotest.setText(QCoreApplication.translate("MainWindow", u"AutoTest", None))
        self.D2_btn_telnet.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u6a21\u5f0f", None))
        self.D2_btn_reboot.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u8bdd\u673a", None))
        self.D2_btn_factory.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u51fa\u5382", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u8bdd\u673aIP", None))
        self.D2_btn_band.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u8bbe\u5907", None))
        self.D2_lab_state.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u72b6\u6001\uff1a", None))
        self.D2_lab_online.setText(QCoreApplication.translate("MainWindow", u"\u672a\u7ed1\u5b9a", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u4fe1\u606f", None))
        self.D2_check_3cx0.setText(QCoreApplication.translate("MainWindow", u"3cx 1500", None))
        self.D2_check_3cx1.setText(QCoreApplication.translate("MainWindow", u"3cx 1501", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u8bbe\u59072", None))
    # retranslateUi

