# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(209, 856)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(6, 9, 201, 751))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 181, 131))
        self.D1_text_ip = QLineEdit(self.groupBox_2)
        self.D1_text_ip.setObjectName(u"D1_text_ip")
        self.D1_text_ip.setGeometry(QRect(62, 20, 111, 20))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 41, 16))
        self.D1_btn_band = QPushButton(self.groupBox_2)
        self.D1_btn_band.setObjectName(u"D1_btn_band")
        self.D1_btn_band.setGeometry(QRect(10, 80, 131, 23))
        self.D1_lab_state = QLabel(self.groupBox_2)
        self.D1_lab_state.setObjectName(u"D1_lab_state")
        self.D1_lab_state.setGeometry(QRect(10, 110, 54, 12))
        self.D1_lab_online = QLabel(self.groupBox_2)
        self.D1_lab_online.setObjectName(u"D1_lab_online")
        self.D1_lab_online.setGeometry(QRect(80, 110, 54, 12))
        self.D1_box_password = QComboBox(self.groupBox_2)
        self.D1_box_password.setObjectName(u"D1_box_password")
        self.D1_box_password.setGeometry(QRect(10, 50, 161, 22))
        self.D1_btn_web = QPushButton(self.groupBox_2)
        self.D1_btn_web.setObjectName(u"D1_btn_web")
        self.D1_btn_web.setGeometry(QRect(140, 80, 31, 23))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 150, 181, 141))
        self.D1_btn_autotest = QPushButton(self.groupBox_3)
        self.D1_btn_autotest.setObjectName(u"D1_btn_autotest")
        self.D1_btn_autotest.setGeometry(QRect(10, 20, 75, 23))
        self.D1_btn_telnet = QPushButton(self.groupBox_3)
        self.D1_btn_telnet.setObjectName(u"D1_btn_telnet")
        self.D1_btn_telnet.setGeometry(QRect(100, 20, 75, 23))
        self.D1_btn_reboot = QPushButton(self.groupBox_3)
        self.D1_btn_reboot.setObjectName(u"D1_btn_reboot")
        self.D1_btn_reboot.setGeometry(QRect(10, 50, 75, 23))
        self.D1_btn_factory = QPushButton(self.groupBox_3)
        self.D1_btn_factory.setObjectName(u"D1_btn_factory")
        self.D1_btn_factory.setGeometry(QRect(100, 50, 75, 23))
        self.D1_btn_logserver = QPushButton(self.groupBox_3)
        self.D1_btn_logserver.setObjectName(u"D1_btn_logserver")
        self.D1_btn_logserver.setGeometry(QRect(10, 80, 75, 23))
        self.D1_btn_7 = QPushButton(self.groupBox_3)
        self.D1_btn_7.setObjectName(u"D1_btn_7")
        self.D1_btn_7.setGeometry(QRect(10, 110, 75, 23))
        self.D1_btn_6 = QPushButton(self.groupBox_3)
        self.D1_btn_6.setObjectName(u"D1_btn_6")
        self.D1_btn_6.setGeometry(QRect(100, 80, 75, 23))
        self.D1_btn_8 = QPushButton(self.groupBox_3)
        self.D1_btn_8.setObjectName(u"D1_btn_8")
        self.D1_btn_8.setGeometry(QRect(100, 110, 75, 23))
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 300, 181, 111))
        self.D1_text_fw = QLineEdit(self.groupBox)
        self.D1_text_fw.setObjectName(u"D1_text_fw")
        self.D1_text_fw.setGeometry(QRect(60, 20, 111, 20))
        self.D1_btn_ap = QPushButton(self.groupBox)
        self.D1_btn_ap.setObjectName(u"D1_btn_ap")
        self.D1_btn_ap.setGeometry(QRect(10, 80, 161, 23))
        self.D1_text_cfg = QLineEdit(self.groupBox)
        self.D1_text_cfg.setObjectName(u"D1_text_cfg")
        self.D1_text_cfg.setGeometry(QRect(60, 50, 111, 20))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 54, 12))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 50, 54, 12))
        self.label_5.setFrameShape(QFrame.NoFrame)
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 530, 181, 81))
        self.D1_btn_register = QPushButton(self.groupBox_4)
        self.D1_btn_register.setObjectName(u"D1_btn_register")
        self.D1_btn_register.setGeometry(QRect(10, 50, 161, 23))
        self.D1_box_register = QComboBox(self.groupBox_4)
        self.D1_box_register.setObjectName(u"D1_box_register")
        self.D1_box_register.setGeometry(QRect(10, 20, 161, 22))
        self.groupBox_9 = QGroupBox(self.tab)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 420, 181, 101))
        self.label_2 = QLabel(self.groupBox_9)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 54, 12))
        self.label_3 = QLabel(self.groupBox_9)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(90, 20, 54, 12))
        self.D1_text_pnum = QLineEdit(self.groupBox_9)
        self.D1_text_pnum.setObjectName(u"D1_text_pnum")
        self.D1_text_pnum.setGeometry(QRect(10, 40, 71, 20))
        self.D1_text_pvalue = QLineEdit(self.groupBox_9)
        self.D1_text_pvalue.setObjectName(u"D1_text_pvalue")
        self.D1_text_pvalue.setGeometry(QRect(90, 40, 81, 20))
        self.D1_btn_pselect = QPushButton(self.groupBox_9)
        self.D1_btn_pselect.setObjectName(u"D1_btn_pselect")
        self.D1_btn_pselect.setGeometry(QRect(10, 70, 41, 23))
        self.D1_btn_pset = QPushButton(self.groupBox_9)
        self.D1_btn_pset.setObjectName(u"D1_btn_pset")
        self.D1_btn_pset.setGeometry(QRect(120, 70, 51, 23))
        self.D1_btn_ptxt = QPushButton(self.groupBox_9)
        self.D1_btn_ptxt.setObjectName(u"D1_btn_ptxt")
        self.D1_btn_ptxt.setGeometry(QRect(60, 70, 51, 23))
        self.groupBox_10 = QGroupBox(self.tab)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 620, 181, 51))
        self.D1_btn_savescreen = QPushButton(self.groupBox_10)
        self.D1_btn_savescreen.setObjectName(u"D1_btn_savescreen")
        self.D1_btn_savescreen.setGeometry(QRect(10, 20, 51, 23))
        self.D1_btn_savelog = QPushButton(self.groupBox_10)
        self.D1_btn_savelog.setObjectName(u"D1_btn_savelog")
        self.D1_btn_savelog.setGeometry(QRect(70, 20, 41, 23))
        self.D1_btn_savecfg = QPushButton(self.groupBox_10)
        self.D1_btn_savecfg.setObjectName(u"D1_btn_savecfg")
        self.D1_btn_savecfg.setGeometry(QRect(120, 20, 51, 23))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_13 = QGroupBox(self.tab_2)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 530, 181, 81))
        self.D2_btn_register = QPushButton(self.groupBox_13)
        self.D2_btn_register.setObjectName(u"D2_btn_register")
        self.D2_btn_register.setGeometry(QRect(10, 50, 161, 23))
        self.D2_box_register = QComboBox(self.groupBox_13)
        self.D2_box_register.setObjectName(u"D2_box_register")
        self.D2_box_register.setGeometry(QRect(10, 20, 161, 22))
        self.groupBox_15 = QGroupBox(self.tab_2)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 10, 181, 131))
        self.D2_text_ip = QLineEdit(self.groupBox_15)
        self.D2_text_ip.setObjectName(u"D2_text_ip")
        self.D2_text_ip.setGeometry(QRect(62, 20, 111, 20))
        self.label_12 = QLabel(self.groupBox_15)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 20, 41, 16))
        self.D2_btn_band = QPushButton(self.groupBox_15)
        self.D2_btn_band.setObjectName(u"D2_btn_band")
        self.D2_btn_band.setGeometry(QRect(10, 80, 131, 23))
        self.D1_lab_state_3 = QLabel(self.groupBox_15)
        self.D1_lab_state_3.setObjectName(u"D1_lab_state_3")
        self.D1_lab_state_3.setGeometry(QRect(10, 110, 54, 12))
        self.D2_lab_online = QLabel(self.groupBox_15)
        self.D2_lab_online.setObjectName(u"D2_lab_online")
        self.D2_lab_online.setGeometry(QRect(80, 110, 54, 12))
        self.D2_box_password = QComboBox(self.groupBox_15)
        self.D2_box_password.setObjectName(u"D2_box_password")
        self.D2_box_password.setGeometry(QRect(10, 50, 161, 22))
        self.D2_btn_web = QPushButton(self.groupBox_15)
        self.D2_btn_web.setObjectName(u"D2_btn_web")
        self.D2_btn_web.setGeometry(QRect(140, 80, 31, 23))
        self.groupBox_16 = QGroupBox(self.tab_2)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(10, 150, 181, 141))
        self.D2_btn_autotest = QPushButton(self.groupBox_16)
        self.D2_btn_autotest.setObjectName(u"D2_btn_autotest")
        self.D2_btn_autotest.setGeometry(QRect(10, 20, 75, 23))
        self.D2_btn_telnet = QPushButton(self.groupBox_16)
        self.D2_btn_telnet.setObjectName(u"D2_btn_telnet")
        self.D2_btn_telnet.setGeometry(QRect(100, 20, 75, 23))
        self.D2_btn_reboot = QPushButton(self.groupBox_16)
        self.D2_btn_reboot.setObjectName(u"D2_btn_reboot")
        self.D2_btn_reboot.setGeometry(QRect(10, 50, 75, 23))
        self.D2_btn_factory = QPushButton(self.groupBox_16)
        self.D2_btn_factory.setObjectName(u"D2_btn_factory")
        self.D2_btn_factory.setGeometry(QRect(100, 50, 75, 23))
        self.D2_btn_logserver = QPushButton(self.groupBox_16)
        self.D2_btn_logserver.setObjectName(u"D2_btn_logserver")
        self.D2_btn_logserver.setGeometry(QRect(10, 80, 75, 23))
        self.pushButton_16 = QPushButton(self.groupBox_16)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(10, 110, 75, 23))
        self.pushButton_17 = QPushButton(self.groupBox_16)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(100, 80, 75, 23))
        self.pushButton_18 = QPushButton(self.groupBox_16)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(100, 110, 75, 23))
        self.groupBox_17 = QGroupBox(self.tab_2)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(10, 300, 181, 111))
        self.D2_text_fw = QLineEdit(self.groupBox_17)
        self.D2_text_fw.setObjectName(u"D2_text_fw")
        self.D2_text_fw.setGeometry(QRect(60, 20, 111, 20))
        self.D2_btn_ap = QPushButton(self.groupBox_17)
        self.D2_btn_ap.setObjectName(u"D2_btn_ap")
        self.D2_btn_ap.setGeometry(QRect(10, 80, 161, 23))
        self.D2_text_cfg = QLineEdit(self.groupBox_17)
        self.D2_text_cfg.setObjectName(u"D2_text_cfg")
        self.D2_text_cfg.setGeometry(QRect(60, 50, 111, 20))
        self.label_13 = QLabel(self.groupBox_17)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 20, 54, 12))
        self.label_14 = QLabel(self.groupBox_17)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 50, 54, 12))
        self.label_14.setFrameShape(QFrame.NoFrame)
        self.groupBox_18 = QGroupBox(self.tab_2)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 420, 181, 101))
        self.label_15 = QLabel(self.groupBox_18)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 20, 54, 12))
        self.label_16 = QLabel(self.groupBox_18)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(90, 20, 54, 12))
        self.D2_text_pnum = QLineEdit(self.groupBox_18)
        self.D2_text_pnum.setObjectName(u"D2_text_pnum")
        self.D2_text_pnum.setGeometry(QRect(10, 40, 71, 20))
        self.D2_text_pvalue = QLineEdit(self.groupBox_18)
        self.D2_text_pvalue.setObjectName(u"D2_text_pvalue")
        self.D2_text_pvalue.setGeometry(QRect(90, 40, 81, 20))
        self.D2_btn_pselect = QPushButton(self.groupBox_18)
        self.D2_btn_pselect.setObjectName(u"D2_btn_pselect")
        self.D2_btn_pselect.setGeometry(QRect(10, 70, 41, 23))
        self.D2_btn_pset = QPushButton(self.groupBox_18)
        self.D2_btn_pset.setObjectName(u"D2_btn_pset")
        self.D2_btn_pset.setGeometry(QRect(120, 70, 51, 23))
        self.D2_btn_ptxt = QPushButton(self.groupBox_18)
        self.D2_btn_ptxt.setObjectName(u"D2_btn_ptxt")
        self.D2_btn_ptxt.setGeometry(QRect(60, 70, 51, 23))
        self.groupBox_14 = QGroupBox(self.tab_2)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 620, 181, 51))
        self.D2_btn_savescreen = QPushButton(self.groupBox_14)
        self.D2_btn_savescreen.setObjectName(u"D2_btn_savescreen")
        self.D2_btn_savescreen.setGeometry(QRect(10, 20, 51, 23))
        self.D2_btn_savelog = QPushButton(self.groupBox_14)
        self.D2_btn_savelog.setObjectName(u"D2_btn_savelog")
        self.D2_btn_savelog.setGeometry(QRect(70, 20, 41, 23))
        self.D2_btn_savecfg = QPushButton(self.groupBox_14)
        self.D2_btn_savecfg.setObjectName(u"D2_btn_savecfg")
        self.D2_btn_savecfg.setGeometry(QRect(120, 20, 51, 23))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_5 = QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 181, 131))
        self.D3_text_ip = QLineEdit(self.groupBox_5)
        self.D3_text_ip.setObjectName(u"D3_text_ip")
        self.D3_text_ip.setGeometry(QRect(62, 20, 111, 20))
        self.label_6 = QLabel(self.groupBox_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 20, 41, 16))
        self.D3_btn_band = QPushButton(self.groupBox_5)
        self.D3_btn_band.setObjectName(u"D3_btn_band")
        self.D3_btn_band.setGeometry(QRect(10, 80, 131, 23))
        self.D1_lab_state_2 = QLabel(self.groupBox_5)
        self.D1_lab_state_2.setObjectName(u"D1_lab_state_2")
        self.D1_lab_state_2.setGeometry(QRect(10, 110, 54, 12))
        self.D3_lab_online = QLabel(self.groupBox_5)
        self.D3_lab_online.setObjectName(u"D3_lab_online")
        self.D3_lab_online.setGeometry(QRect(80, 110, 54, 12))
        self.D3_box_password = QComboBox(self.groupBox_5)
        self.D3_box_password.setObjectName(u"D3_box_password")
        self.D3_box_password.setGeometry(QRect(10, 50, 161, 22))
        self.D3_btn_web = QPushButton(self.groupBox_5)
        self.D3_btn_web.setObjectName(u"D3_btn_web")
        self.D3_btn_web.setGeometry(QRect(140, 80, 31, 23))
        self.groupBox_6 = QGroupBox(self.tab_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 300, 181, 111))
        self.D3_text_fw = QLineEdit(self.groupBox_6)
        self.D3_text_fw.setObjectName(u"D3_text_fw")
        self.D3_text_fw.setGeometry(QRect(60, 20, 111, 20))
        self.D3_btn_ap = QPushButton(self.groupBox_6)
        self.D3_btn_ap.setObjectName(u"D3_btn_ap")
        self.D3_btn_ap.setGeometry(QRect(10, 80, 161, 23))
        self.D3_text_cfg = QLineEdit(self.groupBox_6)
        self.D3_text_cfg.setObjectName(u"D3_text_cfg")
        self.D3_text_cfg.setGeometry(QRect(60, 50, 111, 20))
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 20, 54, 12))
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 54, 12))
        self.label_8.setFrameShape(QFrame.NoFrame)
        self.groupBox_11 = QGroupBox(self.tab_5)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 620, 181, 51))
        self.D3_btn_savescreen = QPushButton(self.groupBox_11)
        self.D3_btn_savescreen.setObjectName(u"D3_btn_savescreen")
        self.D3_btn_savescreen.setGeometry(QRect(10, 20, 51, 23))
        self.D3_btn_savelog = QPushButton(self.groupBox_11)
        self.D3_btn_savelog.setObjectName(u"D3_btn_savelog")
        self.D3_btn_savelog.setGeometry(QRect(70, 20, 41, 23))
        self.D3_btn_savecfg = QPushButton(self.groupBox_11)
        self.D3_btn_savecfg.setObjectName(u"D3_btn_savecfg")
        self.D3_btn_savecfg.setGeometry(QRect(120, 20, 51, 23))
        self.groupBox_7 = QGroupBox(self.tab_5)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 150, 181, 141))
        self.D3_btn_autotest = QPushButton(self.groupBox_7)
        self.D3_btn_autotest.setObjectName(u"D3_btn_autotest")
        self.D3_btn_autotest.setGeometry(QRect(10, 20, 75, 23))
        self.D3_btn_telnet = QPushButton(self.groupBox_7)
        self.D3_btn_telnet.setObjectName(u"D3_btn_telnet")
        self.D3_btn_telnet.setGeometry(QRect(100, 20, 75, 23))
        self.D3_btn_reboot = QPushButton(self.groupBox_7)
        self.D3_btn_reboot.setObjectName(u"D3_btn_reboot")
        self.D3_btn_reboot.setGeometry(QRect(10, 50, 75, 23))
        self.D3_btn_factory = QPushButton(self.groupBox_7)
        self.D3_btn_factory.setObjectName(u"D3_btn_factory")
        self.D3_btn_factory.setGeometry(QRect(100, 50, 75, 23))
        self.D3_btn_logserver = QPushButton(self.groupBox_7)
        self.D3_btn_logserver.setObjectName(u"D3_btn_logserver")
        self.D3_btn_logserver.setGeometry(QRect(10, 80, 75, 23))
        self.pushButton_5 = QPushButton(self.groupBox_7)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(10, 110, 75, 23))
        self.pushButton_6 = QPushButton(self.groupBox_7)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(100, 80, 75, 23))
        self.pushButton_7 = QPushButton(self.groupBox_7)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(100, 110, 75, 23))
        self.groupBox_12 = QGroupBox(self.tab_5)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 420, 181, 101))
        self.label_10 = QLabel(self.groupBox_12)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 20, 54, 12))
        self.label_11 = QLabel(self.groupBox_12)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 20, 54, 12))
        self.D3_text_pnum = QLineEdit(self.groupBox_12)
        self.D3_text_pnum.setObjectName(u"D3_text_pnum")
        self.D3_text_pnum.setGeometry(QRect(10, 40, 71, 20))
        self.D3_text_pvalue = QLineEdit(self.groupBox_12)
        self.D3_text_pvalue.setObjectName(u"D3_text_pvalue")
        self.D3_text_pvalue.setGeometry(QRect(90, 40, 81, 20))
        self.D3_btn_pselect = QPushButton(self.groupBox_12)
        self.D3_btn_pselect.setObjectName(u"D3_btn_pselect")
        self.D3_btn_pselect.setGeometry(QRect(10, 70, 41, 23))
        self.D3_btn_pset = QPushButton(self.groupBox_12)
        self.D3_btn_pset.setObjectName(u"D3_btn_pset")
        self.D3_btn_pset.setGeometry(QRect(120, 70, 51, 23))
        self.D3_btn_ptxt = QPushButton(self.groupBox_12)
        self.D3_btn_ptxt.setObjectName(u"D3_btn_ptxt")
        self.D3_btn_ptxt.setGeometry(QRect(60, 70, 51, 23))
        self.groupBox_8 = QGroupBox(self.tab_5)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 530, 181, 81))
        self.D3_btn_register = QPushButton(self.groupBox_8)
        self.D3_btn_register.setObjectName(u"D3_btn_register")
        self.D3_btn_register.setGeometry(QRect(10, 50, 161, 23))
        self.D3_box_register = QComboBox(self.groupBox_8)
        self.D3_box_register.setObjectName(u"D3_box_register")
        self.D3_box_register.setGeometry(QRect(10, 20, 161, 22))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.groupBox_19 = QGroupBox(self.tab_6)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 10, 181, 131))
        self.D4_text_ip = QLineEdit(self.groupBox_19)
        self.D4_text_ip.setObjectName(u"D4_text_ip")
        self.D4_text_ip.setGeometry(QRect(62, 20, 111, 20))
        self.label_17 = QLabel(self.groupBox_19)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 20, 41, 16))
        self.D4_btn_band = QPushButton(self.groupBox_19)
        self.D4_btn_band.setObjectName(u"D4_btn_band")
        self.D4_btn_band.setGeometry(QRect(10, 80, 131, 23))
        self.D1_lab_state_4 = QLabel(self.groupBox_19)
        self.D1_lab_state_4.setObjectName(u"D1_lab_state_4")
        self.D1_lab_state_4.setGeometry(QRect(10, 110, 54, 12))
        self.D4_lab_online = QLabel(self.groupBox_19)
        self.D4_lab_online.setObjectName(u"D4_lab_online")
        self.D4_lab_online.setGeometry(QRect(80, 110, 54, 12))
        self.D4_box_password = QComboBox(self.groupBox_19)
        self.D4_box_password.setObjectName(u"D4_box_password")
        self.D4_box_password.setGeometry(QRect(10, 50, 161, 22))
        self.D4_btn_web = QPushButton(self.groupBox_19)
        self.D4_btn_web.setObjectName(u"D4_btn_web")
        self.D4_btn_web.setGeometry(QRect(140, 80, 31, 23))
        self.groupBox_20 = QGroupBox(self.tab_6)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(10, 300, 181, 111))
        self.D4_text_fw = QLineEdit(self.groupBox_20)
        self.D4_text_fw.setObjectName(u"D4_text_fw")
        self.D4_text_fw.setGeometry(QRect(60, 20, 111, 20))
        self.D4_btn_ap = QPushButton(self.groupBox_20)
        self.D4_btn_ap.setObjectName(u"D4_btn_ap")
        self.D4_btn_ap.setGeometry(QRect(10, 80, 161, 23))
        self.D4_text_cfg = QLineEdit(self.groupBox_20)
        self.D4_text_cfg.setObjectName(u"D4_text_cfg")
        self.D4_text_cfg.setGeometry(QRect(60, 50, 111, 20))
        self.label_18 = QLabel(self.groupBox_20)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 20, 54, 12))
        self.label_19 = QLabel(self.groupBox_20)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 50, 54, 12))
        self.label_19.setFrameShape(QFrame.NoFrame)
        self.groupBox_21 = QGroupBox(self.tab_6)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(10, 620, 181, 51))
        self.D4_btn_savescreen = QPushButton(self.groupBox_21)
        self.D4_btn_savescreen.setObjectName(u"D4_btn_savescreen")
        self.D4_btn_savescreen.setGeometry(QRect(10, 20, 51, 23))
        self.D4_btn_savelog = QPushButton(self.groupBox_21)
        self.D4_btn_savelog.setObjectName(u"D4_btn_savelog")
        self.D4_btn_savelog.setGeometry(QRect(70, 20, 41, 23))
        self.D4_btn_savecfg = QPushButton(self.groupBox_21)
        self.D4_btn_savecfg.setObjectName(u"D4_btn_savecfg")
        self.D4_btn_savecfg.setGeometry(QRect(120, 20, 51, 23))
        self.groupBox_22 = QGroupBox(self.tab_6)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.groupBox_22.setGeometry(QRect(10, 150, 181, 141))
        self.D4_btn_autotest = QPushButton(self.groupBox_22)
        self.D4_btn_autotest.setObjectName(u"D4_btn_autotest")
        self.D4_btn_autotest.setGeometry(QRect(10, 20, 75, 23))
        self.D4_btn_telnet = QPushButton(self.groupBox_22)
        self.D4_btn_telnet.setObjectName(u"D4_btn_telnet")
        self.D4_btn_telnet.setGeometry(QRect(100, 20, 75, 23))
        self.D4_btn_reboot = QPushButton(self.groupBox_22)
        self.D4_btn_reboot.setObjectName(u"D4_btn_reboot")
        self.D4_btn_reboot.setGeometry(QRect(10, 50, 75, 23))
        self.D4_btn_factory = QPushButton(self.groupBox_22)
        self.D4_btn_factory.setObjectName(u"D4_btn_factory")
        self.D4_btn_factory.setGeometry(QRect(100, 50, 75, 23))
        self.D4_btn_logserver = QPushButton(self.groupBox_22)
        self.D4_btn_logserver.setObjectName(u"D4_btn_logserver")
        self.D4_btn_logserver.setGeometry(QRect(10, 80, 75, 23))
        self.pushButton_8 = QPushButton(self.groupBox_22)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(10, 110, 75, 23))
        self.pushButton_9 = QPushButton(self.groupBox_22)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(100, 80, 75, 23))
        self.pushButton_10 = QPushButton(self.groupBox_22)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(100, 110, 75, 23))
        self.groupBox_23 = QGroupBox(self.tab_6)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setGeometry(QRect(10, 420, 181, 101))
        self.label_20 = QLabel(self.groupBox_23)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 20, 54, 12))
        self.label_21 = QLabel(self.groupBox_23)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(90, 20, 54, 12))
        self.D4_text_pnum = QLineEdit(self.groupBox_23)
        self.D4_text_pnum.setObjectName(u"D4_text_pnum")
        self.D4_text_pnum.setGeometry(QRect(10, 40, 71, 20))
        self.D4_text_pvalue = QLineEdit(self.groupBox_23)
        self.D4_text_pvalue.setObjectName(u"D4_text_pvalue")
        self.D4_text_pvalue.setGeometry(QRect(90, 40, 81, 20))
        self.D4_btn_pselect = QPushButton(self.groupBox_23)
        self.D4_btn_pselect.setObjectName(u"D4_btn_pselect")
        self.D4_btn_pselect.setGeometry(QRect(10, 70, 41, 23))
        self.D4_btn_pset = QPushButton(self.groupBox_23)
        self.D4_btn_pset.setObjectName(u"D4_btn_pset")
        self.D4_btn_pset.setGeometry(QRect(120, 70, 51, 23))
        self.D4_btn_ptxt = QPushButton(self.groupBox_23)
        self.D4_btn_ptxt.setObjectName(u"D4_btn_ptxt")
        self.D4_btn_ptxt.setGeometry(QRect(60, 70, 51, 23))
        self.groupBox_24 = QGroupBox(self.tab_6)
        self.groupBox_24.setObjectName(u"groupBox_24")
        self.groupBox_24.setGeometry(QRect(10, 530, 181, 81))
        self.D4_btn_register = QPushButton(self.groupBox_24)
        self.D4_btn_register.setObjectName(u"D4_btn_register")
        self.D4_btn_register.setGeometry(QRect(10, 50, 161, 23))
        self.D4_box_register = QComboBox(self.groupBox_24)
        self.D4_box_register.setObjectName(u"D4_box_register")
        self.D4_box_register.setGeometry(QRect(10, 20, 161, 22))
        self.tabWidget.addTab(self.tab_6, "")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 780, 191, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 209, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"HTT", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bdd\u673aIP", None))
        self.D1_btn_band.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u8bbe\u5907", None))
        self.D1_lab_state.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u72b6\u6001\uff1a", None))
        self.D1_lab_online.setText(QCoreApplication.translate("MainWindow", u"\u672a\u7ed1\u5b9a", None))
        self.D1_btn_web.setText(QCoreApplication.translate("MainWindow", u"WEB", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u533a", None))
        self.D1_btn_autotest.setText(QCoreApplication.translate("MainWindow", u"AutoTest", None))
        self.D1_btn_telnet.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u6a21\u5f0f", None))
        self.D1_btn_reboot.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u8bdd\u673a", None))
        self.D1_btn_factory.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u51fa\u5382", None))
        self.D1_btn_logserver.setText(QCoreApplication.translate("MainWindow", u"log server", None))
        self.D1_btn_7.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.D1_btn_6.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.D1_btn_8.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u5347\u7ea7", None))
        self.D1_btn_ap.setText(QCoreApplication.translate("MainWindow", u"AP", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"fw\u8def\u5f84", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"cfg\u8def\u5f84", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u4fe1\u606f", None))
        self.D1_btn_register.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"P\u503c\u914d\u7f6e", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"P\u503c(int)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.D1_btn_pselect.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.D1_btn_pset.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6eP\u503c", None))
        self.D1_btn_ptxt.setText(QCoreApplication.translate("MainWindow", u"P\u503c\u8868", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u533a", None))
        self.D1_btn_savescreen.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe", None))
        self.D1_btn_savelog.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.D1_btn_savecfg.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u8bbe\u59071", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u4fe1\u606f", None))
        self.D2_btn_register.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u8bdd\u673aIP", None))
        self.D2_btn_band.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u8bbe\u5907", None))
        self.D1_lab_state_3.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u72b6\u6001\uff1a", None))
        self.D2_lab_online.setText(QCoreApplication.translate("MainWindow", u"\u672a\u7ed1\u5b9a", None))
        self.D2_btn_web.setText(QCoreApplication.translate("MainWindow", u"WEB", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u533a", None))
        self.D2_btn_autotest.setText(QCoreApplication.translate("MainWindow", u"AutoTest", None))
        self.D2_btn_telnet.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u6a21\u5f0f", None))
        self.D2_btn_reboot.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u8bdd\u673a", None))
        self.D2_btn_factory.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u51fa\u5382", None))
        self.D2_btn_logserver.setText(QCoreApplication.translate("MainWindow", u"log server", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"\u5347\u7ea7", None))
        self.D2_btn_ap.setText(QCoreApplication.translate("MainWindow", u"AP", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"fw\u8def\u5f84", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"cfg\u8def\u5f84", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("MainWindow", u"P\u503c\u914d\u7f6e", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"P\u503c(int)", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.D2_btn_pselect.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.D2_btn_pset.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6eP\u503c", None))
        self.D2_btn_ptxt.setText(QCoreApplication.translate("MainWindow", u"P\u503c\u8868", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u533a", None))
        self.D2_btn_savescreen.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe", None))
        self.D2_btn_savelog.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.D2_btn_savecfg.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u8bbe\u59072", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u8bdd\u673aIP", None))
        self.D3_btn_band.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u8bbe\u5907", None))
        self.D1_lab_state_2.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u72b6\u6001\uff1a", None))
        self.D3_lab_online.setText(QCoreApplication.translate("MainWindow", u"\u672a\u7ed1\u5b9a", None))
        self.D3_btn_web.setText(QCoreApplication.translate("MainWindow", u"WEB", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\u5347\u7ea7", None))
        self.D3_btn_ap.setText(QCoreApplication.translate("MainWindow", u"AP", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"fw\u8def\u5f84", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"cfg\u8def\u5f84", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u533a", None))
        self.D3_btn_savescreen.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe", None))
        self.D3_btn_savelog.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.D3_btn_savecfg.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u533a", None))
        self.D3_btn_autotest.setText(QCoreApplication.translate("MainWindow", u"AutoTest", None))
        self.D3_btn_telnet.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u6a21\u5f0f", None))
        self.D3_btn_reboot.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u8bdd\u673a", None))
        self.D3_btn_factory.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u51fa\u5382", None))
        self.D3_btn_logserver.setText(QCoreApplication.translate("MainWindow", u"log server", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"P\u503c\u914d\u7f6e", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"P\u503c(int)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.D3_btn_pselect.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.D3_btn_pset.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6eP\u503c", None))
        self.D3_btn_ptxt.setText(QCoreApplication.translate("MainWindow", u"P\u503c\u8868", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u4fe1\u606f", None))
        self.D3_btn_register.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u8bbe\u59073", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u8bdd\u673aIP", None))
        self.D4_btn_band.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u8bbe\u5907", None))
        self.D1_lab_state_4.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u72b6\u6001\uff1a", None))
        self.D4_lab_online.setText(QCoreApplication.translate("MainWindow", u"\u672a\u7ed1\u5b9a", None))
        self.D4_btn_web.setText(QCoreApplication.translate("MainWindow", u"WEB", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("MainWindow", u"\u5347\u7ea7", None))
        self.D4_btn_ap.setText(QCoreApplication.translate("MainWindow", u"AP", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"fw\u8def\u5f84", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"cfg\u8def\u5f84", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u533a", None))
        self.D4_btn_savescreen.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe", None))
        self.D4_btn_savelog.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.D4_btn_savecfg.setText(QCoreApplication.translate("MainWindow", u"\u914d\u7f6e", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd\u533a", None))
        self.D4_btn_autotest.setText(QCoreApplication.translate("MainWindow", u"AutoTest", None))
        self.D4_btn_telnet.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u6a21\u5f0f", None))
        self.D4_btn_reboot.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u542f\u8bdd\u673a", None))
        self.D4_btn_factory.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u51fa\u5382", None))
        self.D4_btn_logserver.setText(QCoreApplication.translate("MainWindow", u"log server", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u5f00\u53d1", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("MainWindow", u"P\u503c\u914d\u7f6e", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"P\u503c(int)", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.D4_btn_pselect.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.D4_btn_pset.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6eP\u503c", None))
        self.D4_btn_ptxt.setText(QCoreApplication.translate("MainWindow", u"P\u503c\u8868", None))
        self.groupBox_24.setTitle(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c\u4fe1\u606f", None))
        self.D4_btn_register.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"\u8bbe\u59074", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"message", None))
    # retranslateUi

